project:
  type: book
  output-dir: docs

book:
  title: "Regression Textbook Supplement"
  author: "David Stanley"
  date: "5/30/2023"
  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - references.qmd

bibliography: references.bib

format:
  html: 
    grid:
      body-width: 1200px
    theme: cosmo
    toc-depth: 5
  pdf:
    documentclass: scrreprt

editor: visual

